object_type: global_settings
overrides:
    "aggregate.snowflake.table.names.uppercase": true
    "query.drillthrough.max_rows": 1000
    "xmla.auth.token.enabled": true
    "dataloader.operation.timeout": 11 minutes
    "sml.environment.variables": 
      DB_SCHEMA='adventureworks2012' 
      CONNECTION='con1' 
      CON=con12 
      CON2=con1
      CON4=con1
      CON5=con1
      CON6=con1
      CON7=con1
      CON8=con1
      CON9=con1
      CON10=con1
      CON13=con1
      CON100=con1
      CON101=con1
      SCHEMA='adventureworks2012'
