object_type: global_settings
overrides:
    "aggregate.snowflake.table.names.uppercase": true
    "query.drillthrough.max_rows": 1000
    "xmla.auth.token.enabled": true
    "dataloader.operation.timeout": 11 minutes
    "sml.environment.variables": 
      DB_SCHEMA='adventureworks2012' 
      CONNECTION='con1' 
      CON=con12 
      CON2=con1
      SCHEMA='adventureworks2012'
