object_type: global_settings
overrides:
    "aggregate.snowflake.table.names.uppercase": true
    "query.drillthrough.max_rows": 1000
    "xmla.auth.token.enabled": true
    "dataloader.operation.timeout": 11 minutes
    "sml.environment.variables": 
      "CONNECTION: con1" 
      DB_NAME: atscale
      DB_SCHEMA: adventureworks2012"
